---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Default
    name: Default
    inherits: 
    description: 
  fields:
  - Execute:
      on_entry: update_multiple_vms_tags_and_custom_attributes_from_ldap_entries
