---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - email_addresses:
      value: "[itewk@redhat.com,itewk2@redhat.com]"
  - ldap_treebase:
      value: cn=users,cn=accounts,dc=rhc-lab,dc=iad,dc=redhat,dc=com
  - ldap_filter_attribute:
      value: mail
