---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - email_addresses:
      value: "[]"
  - ldap_filter_attribute:
      value: mail
